version: '2'
services:
    jhiptokomaju-app:
        image: jhiptokomaju
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhiptokomaju-mysql:3306/jhiptokomaju?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://jhiptokomaju-elasticsearch:9200
        ports:
            - 8080:8080
    jhiptokomaju-mysql:
        extends:
            file: mysql.yml
            service: jhiptokomaju-mysql
    jhiptokomaju-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhiptokomaju-elasticsearch
